### ISSUE TITLE
Feature: Classroom locations

### ISSUE THREAD

**Issue by AparaV** [lalaithion/yourcuinfo#1]
Hi,

I have an idea for a new feature - adding the classroom locations for the different lecture and recitation sections. For example, the 11:00-11:50 lecture of APPM 2360 is held at ECCR 265 (not sure if that's accurate for the next semester).

This would be really helpful if someone is deciding to take back-to-back classes. It can help them decide whether the 10 min gap would be enough to cover the distance between 2 lecture halls by walk. For instance, I want to take CSCI 2824 from 9:00-9:50 (at, say, Fleming) followed by ECON 3070 from 10:00-10:50 (at, say, Hale Sciences). It would be impossible for me to get to Hale from Fleming in 10 minutes by walking. So I either need to pick a different timing, or bring my bike/skateboard.

Given how intuitive and easy yourCUinfo is to use, I think this feature is very much essential and would only help more students instead of switching to myCUinfo to check feasibility of timing and locations.

And thank you folks for making this wonderful app!

~Apara (fellow CU student who is disgruntled with the myCUinfo UX)

**Comment by apccurtiss** [comment]
Great idea! I think we already scrape that data, so I'll see if I can add it to the UI.

**Comment by apccurtiss** [comment]
That was faster than I thought. It's done.

**Comment by AparaV** [comment]
Wow! That was fast! Thanks guys!
